### PR TITLE
Fix client clean shutdown logic

### LINKED ISSUE #10: KvStoreClient.close() doesn't release all resources
I keep on doing the following, and the memory of the JVM quickly goes up and eventually crashed due to OOM. I know it is better to reuse the KvStoreClient instance, but closing it should release all the referenced memory.

1. Create KvStoreClient
2. Create a KV
3. Delete a KV
4. Close KvStoreClient

### PR DESCRIPTION
**Pull request by njhill**
It seems the prior logic just never worked as intended, and event loop group does not get shutdown properly (at least in many cases).

This update logic is _even more_ convoluted, but needed to ensure that shutdown of the channel and threads happens as soon as possible, but not before other shutdown operations first complete or timeout (which could include network operations to etcd to revoke leases, close streams, etc.).

Fixes #10

### CODE REVIEW

File: src/main/java/com/ibm/etcd/client/EtcdClient.java [hunk 1]
```diff
@@ -338,32 +336,47 @@ public void close() {
...
-            executeWhenIdle(() -> internalExecutor.shutdownGracefully(0, 1, SECONDS));
-        });
+            executeWhenIdle(() -> internalExecutor.shutdownGracefully(0, 1, SECONDS), false);
+        }, true);
     }
     
-    // used only in clean shutdown logic
-    final Iterable<SingleThreadEventLoop> eventLoops;
-    
     /**
```
Comment (yuzheng21) [inline src/main/java/com/ibm/etcd/client/EtcdClient.java]: it would be better to update this description including `yield`

File: src/main/java/com/ibm/etcd/client/EtcdClient.java [hunk 2]
```diff
@@ -338,32 +336,47 @@ public void close() {
...
-            if(Iterables.all(eventLoops, ex -> ex.pendingTasks() == 0)) task.run();
-            else executeWhenIdle(task);
+            int rt = remainingTasks.get();
+            if(rt == -1) remainingTasks.incrementAndGet();
+            else if(rt > 0) executeWhenIdle(task, yield);
+            else if(yield) internalExecutor.execute(task);
+            else task.run();
+        });
+        internalExecutor.forEach(ex -> {
+            ex.execute(new Runnable() {
```
Comment (yuzheng21) [inline src/main/java/com/ibm/etcd/client/EtcdClient.java]: why not using lambda here `() -> {}`?

Comment (njhill) [reply src/main/java/com/ibm/etcd/client/EtcdClient.java]: because the `Runnable` uses the `this` keyword to re-schedule itself, which you can't do with lambdas

Comment (yuzheng21) [reply src/main/java/com/ibm/etcd/client/EtcdClient.java]: did not see `this` keyword usage here. I tried locally, it compiled without errors. also, line 361 `internalExecutor.forEach(ex -> {` can be simplified to `internalExecutor.forEach(ex -> `, but I am ok with keeping outside `{}` to make it more readable

File: src/main/java/com/ibm/etcd/client/EtcdClient.java (hunk 1 above)
Comment (njhill) [reply src/main/java/com/ibm/etcd/client/EtcdClient.java]: Thanks @yuzheng21. Actually I just pushed a commit which simplifies this to remove the `yield` param altogether - the false case isn't really needed.

File: src/main/java/com/ibm/etcd/client/EtcdClient.java (hunk 2 above)
Comment (njhill) [reply src/main/java/com/ibm/etcd/client/EtcdClient.java]: It's here:
```java
                    if(stel.pendingTasks() > 0) ex.execute(this);
```
I'm surprised that it compiles for you because `this` will then refer to the enclosing `EtcdClient` instance which isn't a `Runnable` (and so can't be passed to the `execute()` method).

But good spot on the braces simplification, i'll push an update with that.

Comment (yuzheng21) [reply src/main/java/com/ibm/etcd/client/EtcdClient.java]: oh, I must have left that out. I am ok with this pr now.
